[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
students_intro = "8icGqXZFXN2eHm8hHTkEgje4e76BpyWD44y1bkaWQz4k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
